In [2]:
import pandas as pd

In [3]:
df_customers=pd.read_csv("customers.csv")

In [4]:
df_orders=pd.read_csv("orders.csv")

In [5]:
df_payments=pd.read_csv("payments.csv")

In [6]:
df_products=pd.read_csv("products.csv")

In [7]:
df_orders

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed
...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed

In [8]:
df_orders.isnull().sum()

OrderID            0
CustomerID         0
OrderDate         35
ProductID          0
Quantity          80
Discount         221
PaymentMethod    452
Status             0
dtype: int64

In [9]:
#percenatge of missing values in each columns
missing_pct = df_orders.isnull().mean() * 100
missing_pct[missing_pct > 0].sort_values(ascending=False)

PaymentMethod    0.901836
Discount         0.440942
Quantity         0.159617
OrderDate        0.069832
dtype: float64

In [10]:
df_customers.isnull().sum()

CustomerID           0
Age                180
City               119
SignupDate           0
CustomerSegment      0
dtype: int64

In [11]:
#customer k table mai kitne column mai kitne percentage value missing hain
df_customers.isnull().mean()*100

CustomerID         0.00
Age                1.80
City               1.19
SignupDate         0.00
CustomerSegment    0.00
dtype: float64

In [12]:
df_customers[['Age','City']].isnull().mean()*100

Age     1.80
City    1.19
dtype: float64

In [13]:
missing_pct=df_customers.isnull().mean()*100
missing_pct[missing_pct>0]

Age     1.80
City    1.19
dtype: float64

In [14]:
df_payments.isnull().sum()

PaymentID         0
OrderID           0
PaymentDate      35
PaymentStatus     0
dtype: int64

In [17]:
missing_pct=df_payments.isnull().mean()*100
missing_pct[missing_pct>0]

PaymentDate    0.07
dtype: float64

In [16]:
df_products.isnull().sum()

ProductID      0
ProductName    0
Category       0
UnitPrice      0
dtype: int64

In [18]:
#checking for outliers

In [19]:
df_orders.describe()

             OrderID     CustomerID     ProductID      Quantity      Discount
count   50120.000000   50120.000000  50120.000000  50040.000000  49899.000000
mean   525003.244872  105543.821788   2009.458799      1.881455      0.075130
std     14433.904231   22079.891005      5.577743      1.078846      0.077492
min    500001.000000  100001.000000   2001.000000     -2.000000      0.000000
25%    512503.750000  102515.000000   2004.000000      1.000000      0.000000
50%    525006.500000  105017.000000   2008.000000      2.000000      0.050000
75%    537501.250000  107510.000000   2014.000000      2.000000      0.100000
max    550000.000000  999999.000000   2020.000000      5.000000      0.300000

In [20]:
df_customers.describe()

         CustomerID          Age
count   10000.00000  9820.000000
mean   105000.50000    41.321487
std      2886.89568    13.802441
min    100001.00000    18.000000
25%    102500.75000    29.000000
50%    105000.50000    41.000000
75%    107500.25000    53.000000
max    110000.00000    65.000000

In [22]:
df_payments.describe()

           PaymentID        OrderID
count   50000.000000   50000.000000
mean   825000.500000  525000.500000
std     14433.901067   14433.901067
min    800001.000000  500001.000000
25%    812500.750000  512500.750000
50%    825000.500000  525000.500000
75%    837500.250000  537500.250000
max    850000.000000  550000.000000

In [23]:
df_products.describe()

        ProductID   UnitPrice
count    20.00000   20.000000
mean   2010.50000   61.400000
std       5.91608   62.836798
min    2001.00000    7.000000
25%    2005.75000   20.250000
50%    2010.50000   45.000000
75%    2015.25000   69.750000
max    2020.00000  260.000000